# Generated by Django 3.1 on 2021-07-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacuna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='crop',
            field=models.CharField(blank=True, choices=[('Banana', 'Banana'), ('Beans', 'Beans'), ('Cassava', 'Cassava'), ('Cocoa', 'Cocoa'), ('Maize', 'Maize'), ('Pearl_millet', 'Pearl Millet')], max_length=100, null=True),
        ),
    ]
