# Generated by Django 3.1 on 2021-05-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacuna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='crop',
            field=models.CharField(choices=[('banana', 'Banana'), ('beans', 'Beans'), ('cassava', 'Cassava'), ('cocoa', 'Cocoa'), ('maize', 'Maize'), ('pearl_millet', 'Pearl Millet')], max_length=100),
        ),
    ]
