# Generated by Django 3.1 on 2021-07-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacuna', '0002_auto_20210715_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='crop',
            field=models.CharField(choices=[('Banana', 'Banana'), ('Beans', 'Beans'), ('Cassava', 'Cassava'), ('Cocoa', 'Cocoa'), ('Maize', 'Maize'), ('Pearl_millet', 'Pearl Millet')], max_length=100),
        ),
    ]
