# Generated by Django 3.1 on 2021-07-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacuna', '0003_auto_20210715_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
